### ISSUE TITLE
Investigate possibility of CAS integration

### ISSUE THREAD

**Issue by abeforgit** [abeforgit/RestoWeb#4]

**Comment by redfast00** [comment]
@ninewise weet daar dingen over

**Comment by ninewise** [comment]
ik weet daar dingen over

**Comment by abeforgit** [comment]
good to know! we zullen u dan wel lastigvallen als we zover zijn

**Comment by redfast00** [comment]
niet mogelijk zonder DICT lastig te vallen iirc
